name: Docker CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  # ---------------- BUILD JOB ----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Backend Image
        run: docker build -t student-backend ./backend

      - name: Build Frontend Image
        run: docker build -t student-frontend ./frontend

      - name: Build Nginx Image
        run: docker build -t student-nginx ./nginx


  # ---------------- TEST JOB ----------------
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Backend Tests
        run: |
          echo "Running backend tests"
          cd backend
          npm install
          npm test

      - name: Run Frontend Tests
        run: |
          echo "Running frontend tests"
          cd frontend
          npm install
          npm test


  # ---------------- DEPLOY JOB ----------------
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/student-backend ./backend

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/student-frontend ./frontend

      - name: Build Nginx Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/student-nginx ./nginx

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/student-backend

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/student-frontend

      - name: Push Nginx Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/student-nginx